# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
# paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
# permalink:           none
# plugins:             [jekyll-sitemap, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Election Officer Training'
description:	       ''
author:              'Office of Elections'

# Permalinks
permalink:           /:short_year/:month/:title/
# baseurl: /

# Fix date/time generation
timezone: America/New_York

### Current domain: training.electionofficers.com

plugins:
  - jekyll-redirect-from